# Generated by Django 4.1.9 on 2023-05-16 13:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("coupons", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="coupon",
            old_name="valid_form",
            new_name="valid_from",
        ),
    ]
