# Generated by Django 4.1.8 on 2023-05-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="product",
            name="shop_produc_id_f21274_idx",
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["slug", "id"], name="shop_produc_slug_ba0e9c_idx"
            ),
        ),
    ]
